# Location= /home/$USER/.config/alacritty/alacritty.toml
import = [
  "~/.config/alacritty/catppuccin-latte.toml"
]

[env]

TERM = "xterm-256color"

[font]

normal = { family = "FantasqueSansM Nerd Font", style = "Regular" }
