[terminal]
vt = 7

[default_session]
command = "tuigreet -t --time-format '%A, %B %d, %Y | %I:%M %p' --asterisks --asterisks-char '_' --theme 'input=lightred;action=lightblue;border=green;action=lightyellow;prompt=white;title=lightgreen;time=lightcyan;button=white;text=lightmangeta' -c Hyprland"
user = "_greeter"
