[[themes]]
name = "default-latte"

[themes.palette]
background = "#eff1f5"
foreground = "#4c4f69"
black = "#eff1f5"
blue = "#1e66f5"
cyan = "#04a5e5"
green = "#40a02b"
magenta = "#8839ef"
red = "#d20f39"
white = "#4c4f69"
yellow = "#df8e1d"
bright_black = "#eff1f5"
bright_blue = "#1e66f5"
bright_cyan = "#04a5e5"
bright_green = "#40a02b"
bright_magenta = "#8839ef"
bright_red = "#d20f39"
bright_white = "#4c4f69"
bright_yellow = "#df8e1d"

[themes.component_style]
selection = { bg = "#ccd0da", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "#ccd0da", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "#6c6f85" }
